### ISSUE TITLE
Invalid 'University' Link Fields in 'Student Admission' and 'Level and Semester Enrollment'"  

### ISSUE THREAD

**Issue by Ali-Alnosairi** [Sana-a-Uni/Academia#47]
## Issue Title
Obsolete 'University' Link Fields in 'Student Admission' and 'Level and Semester Enrollment'

## Description
Hello,

I have identified a residual issue in the 'Student Admission' and 'Level and Semester Enrollment' DocTypes where obsolete link fields still point to the 'University' DocType, which has been permanently removed from the system. This outdated reference may lead to errors and user confusion when interacting with these DocTypes, particularly during data entry and querying processes.

### Details
- **DocTypes Affected:** 'Student Admission' and 'Level and Semester Enrollment'.
- **Issue:** These DocTypes contain link fields that reference the non-existent 'University' DocType, potentially causing errors in forms and reports where these fields are involved.

### Proposed Solutions
1. **Remove the Obsolete Link Fields**: If the 'University' data is no longer necessary, the simplest solution would be to remove these link fields from the affected DocTypes.
2. **Replace with Relevant Data**: If similar data needs to be linked, we could explore replacing the 'University' link fields with alternative relevant fields that are still active in the system.

### Action Required
- A decision on how to proceed with these obsolete fields is needed.

Thank you!

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

### Stacktrace / full error message

```
(paste here)
```

## Additional information
@alshalabi-su
@MSarari

**Comment by mohaltheeb** [comment]
'University' Link Fields in Level and Semester Enrollment Doctype is Deleted See #50 PR 
@Ali-Alnosairi
