### ISSUE TITLE
Change Some Properties of Doctypes: Program Enrollment, Facility, and Academic Status

### ISSUE THREAD

**Issue by EsmailEbrahim** [Sana-a-Uni/Academia#52]
Change following:
- In Program Enrollment:
Field: "Faculty" -> Options from facility to faculty.

- In Academic Status and Facility:
Naming of doctypes to the title.

@mohaltheeb 
@alshalabi-su

**Comment by mohaltheeb** [comment]
'Faculty' Link Fields in Program Enrollment Doctype is Refactoring from Facility to Faculty See #56  PR
@EsmailEbrahim

**Comment by EsmailEbrahim** [comment]
Yes, it is 👍. 
See other notes, thanks @mohaltheeb .

**Comment by mohaltheeb** [comment]
The issue has been fixed See #77 PR
