### ISSUE TITLE
Adding Features for Student, Teacher Assistants, and professor management and Course Assignment for Students, Teacher Assistants, and professor

### ISSUE THREAD

**Issue by atrab-ahmed** [Sana-a-Uni/Academia#6]
I would like to add a set of features to our  academia app. Please implement the following features:

1. Student Management:
   - Create an account for each student, including personal information such as name, email, and date of birth.
   - Record academic information for students, such as university, college, major, and academic level.
   - Track the academic progress of each student based on their academic performance.
   - Add each student to a student group based on their academic level and major.

2. Teacher Assistants and professor management:
   - Create an account for each teacher assistant and professor, including personal information such as name, email, and academic specialization.
   - Assign each professor and teacher assistant to teach specific course or multiple courses.
   - Specify the student groups that each professor or teacher assistant will teach.

3. Course Assignment:
   - Assign courses to students based on their major and current academic level.
   - Update the course assignments for each student based on their major, academic level, and current semester.

I kindly request the development team to consider these features and add them to the existing app.

**Comment by BakrAldubai** [comment]
Thank You @atrab-ahmed. The requested features will be added as soon as possible.
