### ISSUE TITLE
Add a Check Field: 'Active' in 'Program Enrollment' Doctype

### ISSUE THREAD

**Issue by EsmailEbrahim** [Sana-a-Uni/Academia#64]
Add a Check Field: 'Active' in 'Program Enrollment' Doctype to Show if a Program Enrollment is Active or Not.

@alshalabi-su 
@tariqalsrory

**Comment by mohaltheeb** [comment]
Added Enabled Field of Type Check in Program Enrollment Doctype see #65 PR

**Comment by EsmailEbrahim** [comment]
Thank you bro @mohaltheeb 👍
